[project]
name = "day12"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Hariom", email = "hariomacharya1@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.4.6",
    "sentence-transformers>=6.0.1",
]

[project.scripts]
day12 = "day12:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
